---
  - name: Install Open JDK 8
    package:
      name: openjdk-8-jdk
      state: present
    become: yes
  
  - name: Install Eclipse
    snap:
      classic: yes
      name: eclipse

  - name: Install Guake
    package:
      name: guake
      state: present
  
  - name: Install zsh
    package:
      name: zsh
      state: present

  - name: Install git
    package:
      name: git
      state: present

  - name: Install ca-certificates
    package:
      name: ca-certificates
      state: present

  - name: Install curl
    package:
      name: curl
      state: present

  - name: ensure .config directiory is present
    file:
      name: /home/vagrant/.config
      state: directory
      owner: vagrant
      group: vagrant

  - name: make sure autostart directiory is present
    file:
      name: /home/vagrant/.config/autostart
      state: directory
      owner: vagrant
      group: vagrant

  - name: copy Startup applications
    copy:
      src: "{{ role_path }}/files/{{ item }}"
      dest: /home/vagrant/.config/autostart/{{ item }}
      owner: vagrant
      group: vagrant
    with_items:
      - guake.desktop

  - name: Run the Oh-My-Zsh installer
    become_user: vagrant
    become: yes
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: "/home/vagrant/.oh-my-zsh"
  
  - name: Set the theme to pygmalion
    lineinfile:
      path: "/home/vagrant/.zshrc"
      regexp: '^ZSH_THEME='
      line: 'ZSH_THEME="pygmalion"'  
    become_user: vagrant
    become: yes
    
  - name: Reset guake settings
    become_user: vagrant
    become: yes
    shell: dbus-launch dconf reset -f /apps/guake/
    args:
      creates: /home/vagrant/.guake-reset

  - name: Load guake settings
    become_user: vagrant
    become: yes
    shell: dbus-launch dconf load /apps/guake/ < "{{ role_path }}/files/apps-guake.dconf"
    args:
      creates: /home/vagrant/.guake-load

  - name: make sure gradel directiory is present
    file:
      name: /opt/gradle
      state: directory
      owner: vagrant
      group: vagrant

  - name: download Gradle
    unarchive:
      src: https://downloads.gradle-dn.com/distributions/gradle-6.2.1-bin.zip
      remote_src: yes
      dest: /opt/gradle
      owner: vagrant
      group: vagrant
  
  - name: Set GRADLE_HOME
    lineinfile:
      path: "/home/vagrant/.zshrc"
      regexp: '^GRADLE_HOME='
      line: 'GRADLE_HOME="/opt/gradle/gradle-6.2.1"'
    become_user: vagrant
    become: yes

  - name: Set PATH
    lineinfile:
      path: "/home/vagrant/.zshrc"
      regexp: '^PATH='
      line: 'PATH=${GRADLE_HOME}/bin:${PATH}'
    become_user: vagrant
    become: yes

  # - name: upgrade packages -- Last Step, will take a while.  VM can be used now.
  #   apt:
  #     update_cache: yes
  #     upgrade: yes
